dependencies {

    testImplementation project(":eventuate-tram-examples-common")

    testImplementation "io.eventuate.tram.core:eventuate-tram-spring-reactive-jdbc-kafka:$eventuateTramVersion"

    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
}

test {
    forkEvery 1
}
