bootJar.enabled = false
jar.enabled = true

dependencies {
    implementation "io.eventuate.tram.core:eventuate-tram-spring-reactive-commands:$eventuateTramVersion"
    implementation "io.eventuate.tram.core:eventuate-tram-spring-reactive-events:$eventuateTramVersion"

    implementation "org.springframework.boot:spring-boot-starter:$springBootVersion"

    implementation "org.junit.jupiter:junit-jupiter-api"

}
